apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.flask.name }}
  labels:
    app: {{ .Values.flask.name }}
spec:
  type: {{ .Values.flask.service.type }}
  ports:
    - port: {{ .Values.flask.service.port }}
      targetPort: {{ .Values.flask.image.containerPort }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.flask.name }}
