apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.flask.name }}
  labels:
    app: {{ .Values.flask.name }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.flask.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ .Values.flask.name }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: {{ .Values.flask.name }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "nginx.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Values.flask.name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.flask.image.repository }}:{{ .Values.flask.image.tag | default .Chart.AppVersion }}"
          env:
            {{- range .Values.flask.image.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
          imagePullPolicy: {{ .Values.flask.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.flask.image.containerPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
